---
title: "How-To"
output: 
  html_document:
    toc: true
    includes:
      in_header: header.html
---
## Step 1: Create an empty R-package
reate a new R-project in R-Studio: File -> New Package -> New Directory

To initialize the project with a git repository click the checkmark when creating the package. Your project is initialized with a .git folder and a .gitignore

Give your package a name that is accepted as an R-package name:

- only ASCII letters, numbers and '.'
- at least two characters
- start with a letter
- not end with '.'

If you accidentally created the package without a git repository you can either use 

```r
usethis::use_git()
```
or you can initialize an empty git repository from the terminal

```sh
git init
```

## Step 2: Create your research compendium

### Fill out the DESCRIPTION  file

Fill out the fields of the description file, e.g.

```r
Package: finalPackage
Type: Package
Title: Analysis of temperature data from somewhere
Version: 0.1.0
Author: Selina Baldauf
Maintainer: Selina Baldauf <selina.baldauf@fu-berlin.de>
Description: Analysis of temperature data from our research project xyz presented in manuscript abc.
License: GPL-3
Encoding: UTF-8
LazyData: true
```

### Add a license
If you want to add a specific license to your project you can use different functions from the usethis package, e.g. for the gpl-3 license you can use

```r
usethis::use_gpl3_license(name = "Selina Baldauf")
```

This adds LICENSE.md with your name in it to the project and automatically updates the license field in the DESCRIPTION file.

### Add data to your compendium

To add data to your compendium, you can either create a /data folder and import data (e.g. as csv) or, if you want your data in .Rda format (practical because it gets automatically loaded with your package) you can do the following:

```r
# create a dummy dataset for temperature measurements
dummyTempData <- data.frame(id = 1:10, temp=rnorm(10, mean = 15, sd = 2))
usethis::use_data(dummyTempData)
```

### Add an analysis script to your compendium

Add an analysis folder with a Rmarkdown document to your compendium.

### Write an analysis function

Write a function that you need for your analysis in the folder R/
You can group related fuctions together in the same R-script but unrelated functions get their own script.

Here, we create a simple printer function that prints the mean of a vector. We save this function in a new R-Script called myPrinterFunction.R

```r
# a simple printer function for the mean of a vector
printMean <- function(x){
  print(paste0("The mean value is ", mean(x, na.rm = T), "!"))
}
```
## Step 3: Unit testing



[Here](https://www.youtube.com/watch?v=79s3z0gIuFU&list=PLk3B5c8iCV-T4LM0mwEyWIunIunLyEjqM&index=1) you can find a good tutorial showing all the R package building basics and more.

To add package dependencies to your R-package (e.g. ggplot2) you can use 
```r
usethis::use_package("ggplot2")
```
This will add the ggplot2 packages to the Imports field in the DESCRIPTION file, meaning it is imported when you load the package.

## Step 2: Add a readme file
This adds an rmd to the package that can be rendered to github in the readme section.
```r
usethis::use_readme_rmd() # or use_readme_md() if you want to use plain Markdown
```

## Step 2: Import your data and scripts
If you already have data and scripts that you want to use in this package, you can import them now.

Organize them in a way that model, data and R scripts are in separate folders. @Marwick2018 give a good overview on how to structure research compendiums so that it is clear and easy to access to others that want to reproduce your results.

# Setup Git and GitHub

## Step 1: Commit your changes locally

In the `Git` tab (next to build) you can first stage all file and then commit them or you can do it from the command line:

```sh
git add *
git commit -m "initial commit"
```

## Step 2: Initialize your Github repository

You can either do this by manually setting up a git repository and adding this package to the repository or, more conveniently, you can do it using the `usethis` package.
To do this step you need to have a PAT (personal access token) for github added to your .Renviron file. You can find a step by step guide on how to do this in the [Happy Git with R book](https://happygitwithr.com/github-pat.html#github-pat).

```r
usethis::use_github()
```
# Unit testing

create the files and test folders needed by the `thestthat` package

```r
usethis::use_testthat
```

You can then can initialize a basic test file by doing
```r
usethis::use_test() # creates a test for the file that is currently open in RSudio
```

# Setup a Continous Integration (CI) pipeline with GitHub actions

## Setup github actions from R

This creates the basic file structure needed to set up your workflow and automatically adds a R-CMD-check.yaml file
```r
usethis::use_github_actions()
```
If you want to use an action that already exists (e.g. from the r-lib/actions) repository you can do the following:

```r
usethis::use_github_action("render-readme.yaml")
```
This adds the respective file to ./github/workflows

# Add RStudio server with `holepunch`
There is a nice intro for holepunch: [Getting started with holepunch](https://karthik.github.io/holepunch/articles/getting_started.html).
The code below is copied'n'pasted from the [holepunch repo's readme](https://github.com/karthik/holepunch).
```r
remotes::install_github("karthik/holepunch")

write_dockerfile(maintainer = "your_name") 
# To write a Dockerfile. It will automatically pick the date of the last 
# modified file, match it to that version of R and add it here. You can 
# override this by passing r_date to some arbitrary date
# (but one for which a R version exists).

generate_badge() # This generates a badge for your readme.

# ----------------------------------------------
# At this time 🙌 push the code to GitHub 🙌
# ----------------------------------------------

# And click on the badge or use the function below to get the build 
# ready ahead of time.
build_binder()
# 🤞🚀
```

# Links and Further reading
## Ropensci's reproducibility guide 
https://ropensci.github.io/reproducibility-guide/
## Reasearch compendia
### *A guide to making your data analysis more reproducible* (by Karthik Ram)
http://inundata.org/talks/rstd19/#/
### Webinar on research compendia
https://youtu.be/g-W6fEv7Pck


## Git and GitHub
### How to use git and github with R and R-Studio
https://happygitwithr.com/
### Howto use Git branching
https://nvie.com/posts/a-successful-git-branching-model/
https://guides.github.com/introduction/flow/

### Github actions
https://help.github.com/en/actions/building-and-testing-code-with-continuous-integration/about-continuous-integration
https://www.youtube.com/watch?v=F3wZTDmHCFA

### CI with github actions

* Jim Hester on [GitHub Actions with R](https://rstudio.com/resources/rstudioconf-2020/azure-pipelines-and-github-actions/)
* [Getting started](https://help.github.com/en/actions/getting-started-with-github-actions) with GitHub Actions
* [Examples](https://github.com/r-lib/actions) for Actions with R

### Jim Hester (tidy developer) on how to use R with github actions, what is the difference between github actions, Travis CI and others, how to set up different workflows:
https://resources.rstudio.com/rstudio-conf-2020/azure-pipelines-and-github-actions-jim-hester

### How to use an .Rmd document as Readme in github and render it automatically with associated figures on push:
https://www.r-bloggers.com/rendering-your-readme-with-github-actions/
https://www.edwardthomson.com/blog/github_actions_advent_calendar.html

## Unit testing

* [Intro to unit testing in R](https://katherinemwood.github.io/post/testthat/)
* Testing with [<code>testthat</code>](http://r-pkgs.had.co.nz/tests.html)

## Holepunch package for R and Binder
https://karthik.github.io/holepunch/


## Scientific publications
James, Justin. 2012. “10 Classic Mistakes That Plague Software Development Projects.” 2012. https://www.techrepublic.com/blog/10-things/10-classic-mistakes-that-plague-software-development-projects/.

Scheller, Robert M, Brian R Sturtevant, Eric J Gustafson, Brendan C Ward, and David J Mladenoff. 2010. “Increasing the Reliability of Ecological Models Using Modern Software Engineering Techniques.” Frontiers in Ecology and the Environment 8 (5): 253–60. https://doi.org/10.1890/080141.

Baxter, Susan M., Steven W. Day, Jacquelyn S. Fetrow, and Stephanie J. Reisinger. 2006. “Scientific Software Development Is Not an Oxymoron.” PLoS Computational Biology 2 (9): 0975–78. https://doi.org/10.1371/journal.pcbi.0020087.

Merali, Zeeya. 2010. “Computational Science: ...Error.” Nature 467 (7317): 775–77. https://doi.org/10.1038/467775a.

Passig, Kathrin, and Johannes Jander. 2013. Weniger Schlecht Programmieren. O’Reilly.

Storer, Tim. 2017. “Bridging the Chasm: A Survey of Software Engineering Practice in Scientific Programming.” ACM Computing Surveys 50 (4). https://doi.org/10.1145/3084225.

Marwick, Ben, Carl Boettiger, and Lincoln Mullen. 2018. “Packaging Data Analytical Work Reproducibly Using R (and Friends).” American Statistician 72 (1): 80–88. https://doi.org/10.1080/00031305.2017.1375986.
