on:
  push:
    paths:
      - docs/presentation_files/*

name: Render gh-pages

jobs:
  render:
    name: Render gh-pages
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render site
        run: Rscript -e 'rmarkdown::render_site()'
      - name: Commit results
        run: |
          git status
